spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/db_play
    username: root
    password: 123456

  ai:
    dashscope:
      api-key: sk-bcf5573cf310444ab736e44ddfd753e6
  application:
    name: spring-ai-deepseek-demo

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 3
      timeout: 2

mybatis:
  configuration:
    map-underscore-to-camel-case: true
